# ~/.circleci/config.yml
version: 2
# orbs:
#   cypress: cypress-io/cypress@1
# executors:
#   with-chrome:
#     docker:
#       - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
# parallelism: 3
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           executor: with-chrome
#           browser: chrome
jobs:
  build:
    parallelism: 3
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: "Install Dependencies"
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: "Verify Cypress Config"
          command: npm run cy:verify
      - run:
          name: "Run Cypress Test Scripts"
          command: npm run cy:run:chrome
        