# ~/.circleci/config.yml

version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    resource_class: small
        # environment:
        #   TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - run: 
          name: "Install Dependencies"
          command: npm ci
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: "Verify Cypress Config"
          command: npm run cy:verify
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  test1:
    working_directory: ~/tmp
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    resource_class: small
        # environment:
        #   TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running cypress tests 1
          command: $(npm bin)/cypress run --browser chrome --spec cypress/integration/examples/actions.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test2:
    working_directory: ~/tmp
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    resource_class: small
        # environment:
        #   TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running cypress tests 2
          command: $(npm bin)/cypress run --browser chrome --spec cypress/integration/examples/actions1.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test3:
    working_directory: ~/tmp
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    resource_class: small
        # environment:
        #   TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running cypress tests 3
          command: $(npm bin)/cypress run --browser firefox --spec cypress/integration/examples/actions2.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test4:
    working_directory: ~/tmp
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    resource_class: small
        # environment:
        #   TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running cypress tests 4
          command: $(npm bin)/cypress run --browser chrome --spec cypress/integration/examples/aliasing.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
          filters:
            branches:
              only: main
      - test2:
          requires:
            - build
          filters:
            branches:
              only: main
      - test3:
          requires:
            - build
          filters:
            branches:
              only: main
      - test4:
          requires:
            - build
          filters:
            branches:
              only: main



# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# executors:
#   linux_os:
#     docker:
#       - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
# workflows:
#   build:
#     jobs:
#       - cypress/install
#           steps:
#             - checkout
#             - run:
#                 name: "Install Dependencies"
#                 command: npm ci
#             - run:
#                 name: "Verify Cypress Config"
#                 command: npm run cy:verify
#       - cypress/run:
#           name: Chrome
#           requires:
#             - cypress/install
#           executor: linux_os
#           browser: chrome
#           parallel: true
#           parallelism: 3
#       - cypress/run:
#           name: Firefox
#           requires:
#             - cypress/install
#           executor: linux_os
#           browser: firefox
#           parallel: true
#           parallelism: 3
       