version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          parallel: true
          parallelism: 3
          
