# ~/.circleci/config.yml
version: 2
# orbs:
#   cypress: cypress-io/cypress@1
# executors:
#   with-chrome:
#     docker:
#       - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
# parallelism: 3
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           executor: with-chrome
#           browser: chrome
jobs:
  build:
    docker:
      - image: 'navdeeprathore/cypress-chrome-firefox-latest-versions'
    parallelism: 3